[general]
watch_paths = ["~/Downloads"]

[[rules]]
name = "Documentos"
match_extension = ["pdf", "docx", "txt", "tar", "gz"]
destination = "Organizado/Documentos"
action = "move"

[[rules]]
name = "Imágenes"
match_extension = ["jpg", "png", "webp", "jpeg"]
destination = "Organizado/Imagenes"
action = "move"

[[rules]]
name = "Otros"
match_extension = ["mp3", "zip", "py", "tar.gz", "gz"]
destination = "Organizado/Otros"
action = "move"
